receivers:
  otlp:
    protocols:
      http:

  prometheus:
    config:
      scrape_configs:
        - job_name: simple_weather_api
          static_configs:
            - targets:
              - web:9394

exporters:
  logging:

  jaeger:
    endpoint: jaeger:14250
    insecure: true

  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: simple_weather_api

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, jaeger]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [logging, prometheus]
