receivers:
  otlp:
    protocols:
      http:

exporters:
  logging:

  jaeger:
    endpoint: jaeger:14250
    insecure: true

  prometheus:
      endpoint: 0.0.0.0:8889  # Prometheus will scrape this endpoint

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]
